apiVersion: skaffold/v2beta17
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: multi-author-blog/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: multi-author-blog/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: multi-author-blog/post-comments
      context: post-comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: multi-author-blog/questions
      context: questions
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
portForward:
  - resourceType: Service
    resourceName: auth-srv
    port: 3003
    localPort: 3003
  - resourceType: Service
    resourceName: posts-srv
    port: 4000
    localPort: 4000
  - resourceType: Service
    resourceName: post-comments-srv
    port: 5000
    localPort: 5000
  - resourceType: Service
    resourceName: questions-srv
    port: 6000
    localPort: 6000
