apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-comments
  template:
    metadata:
      labels:
        app: post-comments
    spec:
      containers:
        - name: post-comments
          image: multi-author-blog/post-comments
          env:
            - name: POST_COMMENTS_PORT
              value: "5000"
            - name: MONGO_URI
              value: "mongodb://post-comments-mongo-srv:27017/post-comments"
---
apiVersion: v1
kind: Service
metadata:
  name: post-comments-srv
spec:
  selector:
    app: post-comments
  ports:
    - name: post-comments
      protocol: TCP
      port: 5000
      targetPort: 5000
